export const countryOptions = [
  { value: 'Polska', label: 'Polska' },
  { value: 'Niemcy', label: 'Niemcy' },
  { value: 'Czechy', label: 'Czechy' },
  { value: 'Słowacja', label: 'Słowacja' },
  { value: 'Ukraina', label: 'Ukraina' },
  { value: 'Litwa', label: 'Litwa' },
  { value: 'Łotwa', label: 'Łotwa' },
  { value: 'Estonia', label: 'Estonia' },
  { value: 'Węgry', label: 'Węgry' },
  { value: 'Rumunia', label: 'Rumunia' },
  { value: 'Bułgaria', label: 'Bułgaria' },
  { value: 'Austria', label: 'Austria' },
  { value: 'Szwajcaria', label: 'Szwajcaria' },
  { value: 'Francja', label: 'Francja' },
  { value: 'Włochy', label: 'Włochy' },
  { value: 'Hiszpania', label: 'Hiszpania' },
  { value: 'Holandia', label: 'Holandia' },
  { value: 'Belgia', label: 'Belgia' },
  { value: 'Dania', label: 'Dania' },
  { value: 'Szwecja', label: 'Szwecja' },
  { value: 'Norwegia', label: 'Norwegia' },
  { value: 'Finlandia', label: 'Finlandia' },
  { value: 'Wielka Brytania', label: 'Wielka Brytania' },
  { value: 'Irlandia', label: 'Irlandia' },
  { value: 'USA', label: 'USA' },
  { value: 'Kanada', label: 'Kanada' },
]
